# Generated by Django 4.2.4 on 2023-08-11 13:49

# import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ta', 'Танки'), ('He', 'Хилы'), ('DD', 'ДД'), ('Me', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('Bs', 'Кузнецы'), ('Tn', 'Кожевники'), ('PM', 'Изготовители зелий'), ('SM', 'Мастера заклинаний')], default='Ta', max_length=2, verbose_name='Категория')),
                ('head', models.CharField(max_length=192, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction_advertisement', to='adFeed.advertisement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
